# Generated by Django 4.2.9 on 2026-01-09 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, db_index=True, max_length=12, unique=True)),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('vehiculo_marca', models.CharField(max_length=80)),
                ('vehiculo_modelo', models.CharField(max_length=80)),
                ('vehiculo_anio', models.PositiveIntegerField()),
                ('vehiculo_color', models.CharField(max_length=80)),
                ('servicio', models.CharField(choices=[('WRAP', 'Wrap'), ('PPF', 'PPF'), ('WRAP_PPF', 'Wrap + PPF')], default='WRAP', max_length=12)),
                ('estatus', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('PREPARACION', 'Preparación'), ('EN_PROCESO', 'En proceso'), ('CONTROL_CALIDAD', 'Control de calidad'), ('LISTO', 'Listo'), ('ENTREGADO', 'Entregado')], default='RECIBIDO', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('PREPARACION', 'Preparación'), ('EN_PROCESO', 'En proceso'), ('CONTROL_CALIDAD', 'Control de calidad'), ('LISTO', 'Listo'), ('ENTREGADO', 'Entregado')], max_length=20)),
                ('nota', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='taller.ordenservicio')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
