# Generated by Django 4.2.9 on 2026-01-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_ordenservicio_vehiculo_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('cliente_contacto', models.CharField(blank=True, help_text='Teléfono o email', max_length=100)),
                ('fecha', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('SERVICIO', 'Nuevo servicio'), ('PROSPECTO', 'Prospecto')], default='PROSPECTO', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('completada', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
