# Generated by Django 5.2.10 on 2026-01-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance',
            name='estatus',
            field=models.CharField(choices=[('EN_RECEPCION', 'En Recepción'), ('EN_PREPARACION', 'En Preparación'), ('EN_PROCESO', 'En Proceso'), ('PREPARANDO_ENTREGA', 'Preparando Entrega'), ('TRABAJO_TERMINADO', 'Trabajo Terminado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='estatus',
            field=models.CharField(choices=[('EN_RECEPCION', 'En Recepción'), ('EN_PREPARACION', 'En Preparación'), ('EN_PROCESO', 'En Proceso'), ('PREPARANDO_ENTREGA', 'Preparando Entrega'), ('TRABAJO_TERMINADO', 'Trabajo Terminado')], default='EN_RECEPCION', max_length=20),
        ),
    ]
