# Generated by Django 5.2.10 on 2026-01-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0004_alter_avance_estatus_alter_ordenservicio_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
