# Generated by Django 4.2.27 on 2026-01-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0005_ordenservicio_costo_total_ordenservicio_monto_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='testigos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
