# Generated by Django 4.2.27 on 2026-01-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0006_ordenservicio_testigos'),
    ]

    operations = [
        migrations.AddField(
            model_name='avance',
            name='fotos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
