# Generated by Django 4.2.27 on 2026-01-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0007_avance_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance',
            name='nota',
            field=models.TextField(blank=True),
        ),
    ]
