# Generated by Django 4.2.27 on 2026-01-29 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0008_alter_avance_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avance',
            name='fotos',
        ),
        migrations.CreateModel(
            name='FotoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='taller.ordenservicio')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
