# Generated by Django 4.2.27 on 2026-01-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0009_remove_avance_fotos_fotoorden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotoorden',
            options={'ordering': ['numero', '-creado_en']},
        ),
        migrations.AddField(
            model_name='fotoorden',
            name='numero',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
